"""Protocol definitions for dependency injection and type safety."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from symbolchain.facade.SymbolFacade import SymbolFacade

    from src.shared.network import NetworkClient
    from src.wallet import AccountInfo


class WalletProtocol(Protocol):
    """Comprehensive protocol defining the full wallet interface."""

    address: str | None
    network_name: str
    node_url: str
    wallet_dir: Path
    wallet_file: Path
    password: str | None
    facade: SymbolFacade
    XYM_DIVISIBILITY: int
    _network_client: NetworkClient

    def is_first_run(self) -> bool: ...
    def has_wallet(self) -> bool: ...
    def load_wallet_from_storage(self, password: str | None = None) -> None: ...
    def create_wallet(self) -> str: ...
    def import_wallet(self, private_key_hex: str) -> str: ...
    def get_address(self) -> str: ...
    def get_balance(self, address: str | None = None) -> list[dict[str, int]]: ...
    def get_mosaic_name(self, mosaic_id: int | None) -> str: ...
    def get_mosaic_info(self, mosaic_id: str | int) -> dict[str, Any] | None: ...
    def get_mosaic_full_info(self, mosaic_id: int) -> dict[str, Any]: ...
    def get_currency_mosaic_id(self) -> int | None: ...
    def get_transaction_history(self, limit: int = 20) -> list[dict[str, Any]]: ...
    def get_harvesting_status(self) -> dict[str, Any]: ...
    def test_node_connection(self, node_url: str | None = None) -> dict[str, Any]: ...
    def _save_config(self) -> None: ...
    def _migrate_legacy_wallet_to_accounts(self) -> None: ...

    def get_accounts(self) -> list[AccountInfo]: ...
    def get_current_account(self) -> AccountInfo | None: ...
    def get_current_account_index(self) -> int: ...
    def switch_account(self, index: int) -> bool: ...
    def load_current_account(self) -> bool: ...
    def create_account(
        self, label: str = "", address_book_shared: bool = True
    ) -> AccountInfo: ...
    def import_account(
        self, private_key_hex: str, label: str = "", address_book_shared: bool = True
    ) -> AccountInfo: ...
    def update_account_label(self, index: int, label: str) -> bool: ...
    def update_account_address_book_shared(self, index: int, shared: bool) -> bool: ...
    def delete_account(self, index: int) -> bool: ...
    def export_private_key(self, password: str) -> dict[str, Any]: ...
    def import_encrypted_private_key(
        self, encrypted_data: dict[str, Any], password: str
    ) -> None: ...

    def get_addresses(self) -> dict[str, dict[str, Any]]: ...
    def get_address_info(self, address: str) -> dict[str, Any]: ...
    def add_address(
        self,
        address: str,
        name: str,
        note: str = "",
        group_id: str | None = None,
    ) -> None: ...
    def update_address(
        self,
        address: str,
        name: str,
        note: str,
        group_id: str | None = None,
    ) -> None: ...
    def remove_address(self, address: str) -> None: ...

    def get_contact_groups(self) -> dict[str, dict[str, str]]: ...
    def get_contact_group(self, group_id: str) -> dict[str, str] | None: ...
    def create_contact_group(self, name: str, color: str = "") -> str: ...
    def update_contact_group(
        self, group_id: str, name: str, color: str = ""
    ) -> bool: ...
    def delete_contact_group(self, group_id: str) -> bool: ...
